services:

  nodeapp:
    build:
      context: ./node #caminho para o dockerfile do node
      dockerfile: Dockerfile # Nome do dockerfile do node
    depends_on: # Define as dependências do serviço nodeapp
      - mongo   

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx-html:/usr/share/nginx/html
  mongo:
    image: mongo:latest